name: laravel-create-project

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Version
        run: docker version

      - name: Build Docker Images
        run: docker compose build

      - name: Start Docker Containers
        run: docker compose up -d

      - name: OS Version
        run: |
          docker compose exec app cat /etc/os-release
          docker compose exec app cat /etc/debian_version

      - name: PHP Version
        run: docker compose exec app php --version

      - name: Composer Version
        run: docker compose exec app composer --version

      - name: Build Laravel Project
        run: |
          docker compose up -d --build

      - name: Laravel Version
        run: docker compose exec app php artisan --version

      - name: Wait for the MySQL container to start
        run: sleep 5s
        shell: bash

      - name: Laravel Migrate Testing
        run: docker compose exec app php artisan migrate

      - name: Laravel Rollback Testing
        run: docker compose exec app php artisan migrate:refresh

      - name: Laravel Seeding Testing
        run: docker compose exec app php artisan db:seed

      - name: Laravel PHPUnit Testing
        run: docker compose exec app php artisan test

      - name: set docker compose file
        run: |
          cp ./config/docker-compose-prod.yml ./docker-compose.yml

  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: set docker-compose file
        run: cp ./config/docker-compose-prod.yml ./docker-compose.yml
      - name: composer
        run: |
          composer validate
          composer install --no-dev
                - name: composer
        working-directory: ./src
      - name: npm
        run: |
          yarn
          yarn build
        working-directory: ./src
